# Site settings
lang: en-US

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Repository settings; only needed locally
repository: 6XGate/TortoisePlink

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
